testapp/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import *

app_name = 'testapp'

urlpatterns = [
    path('', main, name='main'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('find/', find, name="find"),
    path('accept/<int:pk>', accept, name="accept"),
    path('reject/<int:pk>', reject, name="reject"),
    path('mypage/', mypage, name="mypage"),
    path('follow/<int:pk>', follow, name="follow"),
    path('find_card', find_card, name="find_card"),
    path('get/<int:pk>', get, name="get"),
    path('page/<int:my_id>/<int:other_id>', page, name="page"),
    path('trade/<int:pk>', trade, name="trade"),
    path('tradepage/', tradepage, name="tradepage"),
    # 나의 id와 상대방의 id를 동시에 전달함
    path('tradeaccept/<int:trade_id>/<int:card_id>', tradeaccept, name="tradeaccept"),
    path('attack/', attack, name='attack'),
    path('mypage/cancel_follow/', cancel_follow, name='cancel_follow'),
    #cancel_follow page 추가
    #앞에 mypage가 붙는 이유는 mypage.html에서 button을 눌러 자동으로 붙는다
    #mypage 없앨 수 있는 방법 고민 중
    path('defense/', defense, name='defense'),
]

testapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    nickname = models.CharField(verbose_name='사용자 닉네임', max_length=50)


class Player(models.Model):
    player_name = models.CharField(verbose_name='플레이어 이름', max_length=50)
    photo = models.ImageField(upload_to='player/', blank=True, null=True)
    attack = models.IntegerField(verbose_name='공격력')
    defense = models.IntegerField()
    user = models.ForeignKey(User, related_name='user',
                             on_delete=models.CASCADE, blank=True, null=True)
    trade = models.ManyToManyField(User, related_name="trade", blank = True, null =True)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follower = models.ManyToManyField(
        User, related_name='follower', blank=True)
    following = models.ManyToManyField(
        User, related_name='following', blank=True)
    notyet = models.ManyToManyField(
        User, related_name='notyet', blank=True)

testapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'nickname']

testapp/views.py
from django.http import HttpResponse, JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import render
from .models import *

import random


def main(request):
    user = request.user
    ctx = {
        'user': user
    }
    return render(request, 'main.html', ctx)


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(
                request=request, username=username, password=password)
            if user is not None:
                login(request, user)
            return redirect('/')
        else:
            form = AuthenticationForm()
            ctx = {
                'form': form,
                'error': 'username or password is incorrect'
            }
            return render(request, 'login.html', ctx)

    else:
        form = AuthenticationForm()
        ctx = {
            'form': form
        }
        return render(request, 'login.html', ctx)


def logout_view(request):
    logout(request)
    return redirect('/')


def signup_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            new_profile = Profile()
            new_profile.user = user
            new_profile.save()
            login(request, user)
            return redirect('/')
        else:
            form = RegisterForm()
            ctx = {
                'form': form,
                'error': 'username or password is incorrect'
            }
            return render(request, 'signup.html', ctx)

    else:
        form = RegisterForm()
        ctx = {
            'form': form
        }
        return render(request, 'signup.html', ctx)


def find(request):
    user = request.user
    userlist = list(User.objects.all())
    userlist.remove(user)

    randomuser = random.choice(userlist)

    ctx = {
        'randomuser': randomuser
    }

    return render(request, 'randomuser.html', ctx)


def follow(request, pk):
    user = request.user
    randomuser = User.objects.get(id=pk)
    randprofile = Profile.objects.get(user=randomuser)
    randprofile.notyet.add(user)
    randprofile.save()

    return redirect('/')


def mypage(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    notyetlist = list(profile.notyet.all())
    followers = list(profile.follower.all())
    followings = list(profile.following.all())
    cards = list(Player.objects.filter(user=user))
    ctx = {
        'profile': profile,
        'notyetlist': notyetlist,
        'followers': followers,
        'followings': followings,
        'cards': cards,
    }

    return render(request, 'mypage.html', ctx)


def accept(request, pk):
    user = request.user
    profile = Profile.objects.get(user=user)

    others = User.objects.get(id=pk)
    others_profile = Profile.objects.get(user=others)

    profile.follower.add(others)
    profile.notyet.remove(others)
    profile.save()

    others_profile.following.add(user)
    others_profile.save()
    return redirect('/')


def reject(request, pk):
    user = request.user
    profile = Profile.objects.get(user=user)

    others = User.objects.get(id=pk)
    others_profile = Profile.objects.get(user=others)

    profile.notyet.remove(others)
    profile.save()

    return redirect('/')


def find_card(request):
    user = request.user
    players = list(Player.objects.filter(user=None))
    player = random.choice(players)

    ctx = {
        'player': player
    }

    return render(request, 'randomcard.html', ctx)


def get(request, pk):
    user = request.user
    card = Player.objects.get(id=pk)
    card.user = user
    card.save()

    return redirect('/')


def page(request, my_id, other_id):
    me = request.user
    other = User.objects.get(id=other_id)
    other_profile = Profile.objects.get(user=other)
    cards = list(Player.objects.filter(user=other))
    ctx = {
        'me': me,
        'other': other,
        'cards': cards,

    }
    return render(request, "page.html", ctx)


def trade(request, pk):
    user = request.user
    tradeuser = User.objects.get(id=pk)
    tradecard = Player.objects.get(user=tradeuser)
    tradecard.trade.add(user)
    tradecard.save()

    return redirect('/')


def tradepage(request):
    user = request.user
    cards = list(Player.objects.filter(user=user))
    ctx = {
        'cards': cards
    }

    return render(request, 'trade.html', ctx)


def tradeaccept(request, trade_id, card_id):
    user = request.user
    tradeuser = User.objects.get(id=trade_id)
    tradecard = Player.objects.get(id=card_id)

    tradecard.trade.clear()
    tradecard.user = tradeuser
    tradecard.save()

    return redirect('/')

@csrf_exempt
def attack(request):
    if request.method == 'POST':
        req = json.loads(request.body)
        player_id = req['id']
        player = Player.objects.get(id=player_id)
        player.attack += 10
        player.save()
    return JsonResponse({'id': player_id})

@csrf_exempt
def defense(request):
    if request.method == 'POST':
        req = json.loads(request.body)
        player_id = req['id']
        player = Player.objects.get(id=player_id)
        player.defense -= 10
        player.save()
    return JsonResponse({'id': player_id})


@csrf_exempt #필수
def cancel_follow(request):
    if request.method == 'POST':
        req = json.loads(request.body)
        #req에 dict넣음
        
        my_id = req['my_id']
        other_id = req['other_id']
        #변수에 삽입

        my_profile = Profile.objects.get(id = my_id)
        other_profile = Profile.objects.get(id = other_id)
        
        my_profile.following.remove(other_id)
        other_profile.follower.remove(my_id)
        
        my_following_list = list(my_profile.following.all())
        other_following_list = list(other_profile.follower.all())
        
        my_profile.save()
        other_profile.save()

    return JsonResponse({'my_id': my_id, 'other_id': other_id})

testapp/templates/login.html
<div>
    <h1>hello</h1>
    <h3>LOGIN</h3>
    {% if error %} {{error}} {% endif %}
    <form action="{% url 'testapp:login' %}" method="POST">
        {% csrf_token %} {{form.as_p}}
        <button type="submit">SUBMIT</button>
    </form>
    <a href="{% url 'testapp:main' %}"><button>go to MAIN</button></a>
</div>

testapp/templates/main.html
<h1>hello {{user}}</h1>

<a href="{% url 'testapp:login' %}">login</a>
<a href="{% url 'testapp:signup' %}">signup</a>
<a href="{% url 'testapp:find' %}">find</a>
<a href="{% url 'testapp:find_card' %}">find_card</a>
<a href="{% url 'testapp:mypage' %}">mypage</a>
<script>
    console.log("김주노하");
</script>

testapp/templates/mypage.html
<h1>나를 팔로우하고 싶은 사람</h1>

{% for user in notyetlist %}
<div>
{{user}}
</div>

<a href = "{% url 'testapp:accept' user.id %}"><button>yes</button></a>
<a href = "{% url 'testapp:reject' user.id %}"><button>no</button></a>

{% endfor %}

<h1>팔로워</h1>
{% for follower in followers%}
<div>
{{follower}}
<a href = "{% url 'testapp:page' user.id follower.id%}"><button>view page</button></a>
</div>
{% endfor %}

<h1>팔로잉</h1>
{% for following in followings%}
<div id = "following-{{following.id}}">
<!-- following의 id마다 div의 id를 다르게 하여 각각에 적용 가능 -->
{{following}}
<br>
<a href = "{% url 'testapp:page' user.id following.id%}"><button>view page</button></a>
{% comment %} 나의 아이디와 남의 아이디를 동시에 전달해 trade가 편하게 함 {% endcomment %}
<button onclick = "cancel_follow({{user.id}}, {{following.id}})">Cancel</button>
<!-- 팔로잉과 팔로워를 동시에 없애야 함 -->
<br><br>
</div>
{% endfor %}

<h1>my card</h1>

<!-- {% for card in cards %}
<div>
<img src = "{{card.photo.url}}", width = "600">
</div>
{% endfor %} -->
<!-- 미디어 폴더에 사진 없어서 주석처리함 -->

<a href = "{% url 'testapp:tradepage'%}"><button>trade 요청받은거 확인하기</button></a>

<script>
    const request = new XMLHttpRequest();

    const cancel_follow = (my_id, other_id) => {   
        const url = "cancel_follow/";
        // 이렇게 하니 현재 페이지에 cancel_follow가 붙음
        request.open("POST", url, true);
        request.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        request.send(JSON.stringify({my_id, other_id}));
        // 여러 변수를 한 번에 보냄
    };

    const handleResponse = () => {
        if (request.status <= 400) {
            const {my_id, other_id} = JSON.parse(request.response)
            // views에 썼던 JsonResponse에 간 변수들을 받아옴
            const element = document.querySelector(`#following-${other_id}`);
            // backtick을 써야 변수를 포함할 수 있음
            element.style = "display:none";
        }
    };

    request.onreadystatechange = () => {
        if (request.readyState === XMLHttpRequest.DONE) {
            handleResponse();
        }
    };
</script>

testapp/templates/page.html
<h1>Hi {{me.nickname}}! This is {{other.nickname}}'s page</h1>
{% comment %} trade의 주체가 누구인지 표현 함 {% endcomment %}

<h2>Card List</h2>

{% for card in cards %}
<div>
    <img src="{{card.photo.url}}" , alt="" , width="300" />
    <a href="{% url 'testapp:trade' other.id %}"><button>trade</button></a>
    {% comment %} 화이팅! {% endcomment %}
</div>
{% endfor %}

testapp/templates/randomcard.html
{{player.player_name}}
<p id="attack_number">attack {{player.attack}}</p>
<p id='defense_number'>defense {{player.defense}}</p>

<img src="{{player.photo.url}}" , alt="" width="600" />

<a href="{% url 'testapp:get' player.id %}"><button>Get</button></a>

<button onclick="attack({{player.id}})">공격력을 올리기!</button>
<button onclick="defense({{player.id}})" id = "defense_comment">방어력 낮추기!</button>

<script>
    const request = new XMLHttpRequest();

    const attack = (id) => {
        const url = "attack/";
        request.open("POST", url, true);
        request.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        request.send(JSON.stringify({ id }));
    };

    const handleResponse = () => {
        if (request.status <= 400) {
            const element = document.querySelector("#attack_number");
            const attack_num = Number(element.innerText.split(" ")[1]);
            const revised_num = attack_num + 10;
            element.innerText = "attack " + revised_num;
        }
    };
    

    request.onreadystatechange = () => {
        if (request.readyState === XMLHttpRequest.DONE) {
            handleResponse();
        }
    };
</script>

<script>
    const request_defense = new XMLHttpRequest();

    const defense = (id) => {
        const url = "defense/";
        request_defense.open("POST", url, true);
        request_defense.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        request_defense.send(JSON.stringify({ id }));
    };

    const handleResponse_defense = () => {
    // const 다른 이름 써야함
        if (request_defense.status <= 400) {
            const element_num = document.getElementById("defense_number");
            // document.getElementById(" ") #없이 id 선택 가능
            const defense_num = Number(element_num.innerText.split(" ")[1]);
            const subtract_num = defense_num - 10;
            element_num.innerText = "defense " + subtract_num;
            const element_button= document.getElementById("defense_comment");
            element_button.innerText = "방어력 낮췄다!";
            // 방어력 낮췄다!는 새로고침 시 방어력 낮추기!로 다시 바뀜
        }
    };

    request_defense.onreadystatechange = () => {
        if (request_defense.readyState === XMLHttpRequest.DONE) {
            handleResponse_defense();
            // request 와 handleResponse 에 해당하는 함수명 통일
        }
    };
</script>

testapp/templates/randomuser.html
{{randomuser.nickname}}

<a href = "{% url 'testapp:follow' randomuser.id %}"><button>follow</button></a> 

testapp/templates/signup.html
<div>
    <h1>hello</h1>
    <h3>SIGNUP</h3>
    {% if error %} {{error}} {% endif %}

    <form action="{% url 'testapp:signup' %}" method="POST">
        {% csrf_token %} {{form.as_p}}
        <button type="submit">SUBMIT</button>
    </form>
    <a href="{% url 'testapp:main' %}"><button>go to MAIN</button></a>
</div>

testapp/templates/trade.html
<h1>trade 요청 받은 카드</h1>

{% for card in cards %}
<div>
{{card.trade.user}}
<img src = "{{card.photo.url}}", width = "600">

{% comment %} trade 요청을 보내온 모든 user를 불러옴, 그 중에서 선택하여 accept {% endcomment %}
{% for trade in card.trade.all %}
<p> {{trade}} </p>
<a href = "{% url 'testapp:tradeaccept' trade.id card.id %}"><button>accept trade</button></a>
{% endfor %}
</div>



{% endfor %}